name: 'RunWatch GitHub Reporter'
description: 'Report workflow and job metrics to the RunWatch Pipeline Pulse Portal'
author: 'RunWatch'

inputs:
  runwatch_api_url:
    description: 'URL of the RunWatch ingestion API endpoint'
    required: false
    default: 'https://api.runwatch.io/v1/ingest'
  runwatch_api_key:
    description: 'API Key or Token for authentication with the RunWatch API'
    required: true
  workflow_run_id:
    description: 'The GitHub Actions workflow run ID to report metrics for (if not provided, the current run ID will be used)'
    required: false
    default: ${{ github.run_id }}
  dry_run:
    description: 'If true, just log the JSON payload instead of posting it to the RunWatch API'
    required: false
    default: 'false'
  debug:
    description: 'If true, log additional debug information'
    required: false
    default: 'false'

outputs:
  pipeline_run_id:
    description: 'The GitHub Actions workflow run ID that was reported'
  status:
    description: 'The reported pipeline status (e.g. success, failure, cancelled)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'blue'

